### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/handover#73]
Today it's hardcoded in the blade template. It should be more dynamic to allow other divisions to adjust to their needs.

- [x] Theme colors
- [x] Theme DPP details
- [x] Logo
- [x] Login text
- [ ] ~~Might be we should upgrade Bootstrap once we're at on it as well.~~

**Comment by bedrich-schindler** [comment]
We upvote this issue. Our login page looks like this:

<img width="597" alt="image" src="https://github.com/Vatsim-Scandinavia/handover/assets/10213870/91828a6c-8a32-4723-a105-59b272d2e054">

We currently need at least possibility to specify logo using `.env` file as it is in Control Center as we do not have SVG logo and it seems quite weird as our ATC does not know to which service do they log in. Possibility to change texts on the login form would be nice as well.

Theming is nice, but not priority for us. Do you plan to work on this issue or should I create separate issue for those high-priority things?

**Comment by blt950** [comment]
Logo and login texts would be part of theming as well, added it to the checklist. Just keep in mind that in next version the user will not really see Handover anymore unless they visit it explicitly #70 

Is that what you meant, or what other "high-priority things" did you have in mind @bedrich-schindler ?

**Comment by blt950** [comment]
Added in #79 will be available in new release soon.
